### ISSUE TITLE
fluorinejs.org is down

### ISSUE THREAD

**Issue by j4ckcyw** [philpl/fluorine#25]
Unable to connect https://fluorinejs.org/
isitdown http://www.isitdownrightnow.com/fluorinejs.org.html

**Comment by philpl** [comment]
Thanks for reporting! I'll get it back up as quickly as possible

**Comment by philpl** [comment]
@j4ckcyw The site should be back up now, but I'm still working on restoring the slack inviter. Thanks again for noticing
