### ISSUE TITLE
Counter example rollback not working

### ISSUE THREAD

**Issue by j4ckcyw** [philpl/fluorine#27]
The "increment async and rollback" button does not show an increment first then rollback it. Here is the log. From the log, it seems both delay 1s kick off at the same time, instead of being sequential.

```js
%c Store counter @ 12:00:23.91 color: #111111;
 agenda Object { _isScalar: false, source: Object, operator: Object }
 action Object { type: "INCREMENT_COUNTER" }
 change 1
%c Error Agenda Observable @ 12:00:22.89 (in 1031ms) color: #111111;
 agenda Object { _isScalar: false, source: Object, operator: Object }
 error Hello World!
 dispatched actions Array [ Object ]
%c Revert counter @ 12:00:23.137 color: #f20404;
 agenda Object { _isScalar: false, source: Object, operator: Object }
 previous 1
 state 0
 error Hello World!
 bucket Array [ Object ]
```

**Comment by philpl** [comment]
Fixed in https://github.com/philpl/fluorine/commit/606cb5330c11729476447244234bf120c0deef21

Thanks again for being so thorough. The slack invitation stuff doesn't currently work unfortunately, but if you're interested in having chats about fluorine I can send you an invite manually ;)
