### ISSUE TITLE
Write some useful Documentation

### ISSUE THREAD

**Issue by philpl** [philpl/fluorine#3]
There are a couple of documentation left to do. The API docs is kind of done and just needs some more references to other files.

Some docs that need to be written are:

- [x] Concepts
- [x] Glossary
- [ ] Agenda Tips and Tricks
- [ ] A comparison to Flux
- [ ] A comparison to Redux
- [ ] How to use or avoid Decorators
- [x] Add API docs for distinctSelector
- [ ] Add API docs for combineReducers
- [ ] Add formulas / guides for setting up various project structures

**Comment by kdart** [comment]
Greetings. This looks interesting. I'm trying to put something together along these lines. But I'm a little unclear on something. If I use fluorine, then I do *not* use redux? Or do I? 

I'm also going to use a JSON-API library [json-api-store](http://particlesystem.com/json-api-store/docs/v0.7.0/). That one already uses Rx and returns Observables. So it seems these would work well together.  Do you have any examples of this? Thanks.

**Comment by philpl** [comment]
@kdart The documentation is unfortunately far from done, but there's some good stuff inside it that is worth checking out:https://github.com/philpl/fluorine/blob/master/docs/README.md

Checkout the concepts part. It's an extensive overview over the entire library. 

With Fluorine you do not use Redux, however it shares a lot of ideas and patterns. The main difference is that you're not using a single store, but like in Flux multiple ones and that stores are just observables emitting state. The dispatcher is under your control as well btw, as it is manually created using a factory function and also just an observable. 

And to round it up, there's side effect management with observables.

There's two examples here in the repo, that should help you. The counter one is easy to grasp https://github.com/philpl/fluorine/tree/master/examples

BTW would it help you to have a slack channel or something where you can ask questions?
