### ISSUE TITLE
Improve compatibility to other versions of RxJS and other ES7-spec observables

### ISSUE THREAD

**Issue by philpl** [philpl/fluorine#7]

**Comment by rgbkrk** [comment]
Speaking only for myself here, I'm happy you're on RxJS 5 since that's what I'm using all over now.

**Comment by philpl** [comment]
@rgbkrk Yea, I'm not planning to move away from RxJS, but it'd be nice to add a conversion, so that other ES7-compliant Observable implementations work :)

I think it might be a matter of just doing: `new Observable((...args) => foreign.subscribe(...args))`
